/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:2192: Warning: MongosMemory,ZoneList,ConfigServerNodeNum,MongosNodeNum,ConfigServerCpuNum,InstanceTaskId,ConfigServerVolume,ConfigServerMemory,InstanceTaskDesc,MongosCpuNum fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:1202: Warning: Region fileds are useless.
2022-03-08 05:32:36,480 - Traceback (most recent call last):
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/data/python37/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/data/python37/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/data/python37/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/data/python37/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/data/python37/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/python37/lib/python3.7/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/data/python37/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/work/dba-in-cloud/libs/myconcurrent.py", line 60, in __single_thread_exe
    self.target(**arg)
  File "/data/work/dba-in-cloud/libs/utils.py", line 99, in download_file_ex
    for data in response.iter_content(chunk_size=chunk_size):
  File "/data/python37/lib/python3.7/site-packages/requests/models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com', port=443): Read timed out.

2022-03-08 05:32:36,496 - fail function use [ {'url': 'https://cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com/cmgo-7ozf7yh1_2022-03-08%2001%3A15%2Fcmgo-7ozf7yh1_0.tar?q-sign-algorithm=sha1&q-ak=AKIDhoeKsEVYVaa2zldwGPUOFVaVIuLdHpTw&q-sign-time=1646684349%3B1646770749&q-key-time=1646684349%3B1646770749&q-header-list=host&q-url-param-list=&q-signature=1a28c221a79078f9937f7316a0dd68d7210bd5f0', 'path': '/data/backup/mongodb/full', 'filename': 'Golden-base-bridge-prod_20220308.tar', 'download_timeout': 1800, 'region': 'ap-guangzhou', 'instance_id': 'cmgo-7ozf7yh1', 'backup_name': 'cmgo-7ozf7yh1_2022-03-08 01:15'} ]
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: BackupMethod,TaskId,StartTime,BackupDesc,Bucket,UpdateTime,Region,InstanceId fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:2192: Warning: ConfigServerVolume,MongosNodeNum,InstanceTaskId,ZoneList,ConfigServerNodeNum,ConfigServerCpuNum,InstanceTaskDesc,MongosCpuNum,MongosMemory,ConfigServerMemory fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:1202: Warning: Region fileds are useless.
2022-03-10 05:37:43,098 - Traceback (most recent call last):
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/data/python37/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/data/python37/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/data/python37/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/data/python37/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/data/python37/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/python37/lib/python3.7/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/data/python37/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/work/dba-in-cloud/libs/myconcurrent.py", line 60, in __single_thread_exe
    self.target(**arg)
  File "/data/work/dba-in-cloud/libs/utils.py", line 99, in download_file_ex
    for data in response.iter_content(chunk_size=chunk_size):
  File "/data/python37/lib/python3.7/site-packages/requests/models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com', port=443): Read timed out.

2022-03-10 05:37:43,109 - fail function use [ {'url': 'https://cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com/cmgo-7ozf7yh1_2022-03-10%2001%3A13%2Fcmgo-7ozf7yh1_0.tar?q-sign-algorithm=sha1&q-ak=AKIDhoeKsEVYVaa2zldwGPUOFVaVIuLdHpTw&q-sign-time=1646857146%3B1646943546&q-key-time=1646857146%3B1646943546&q-header-list=host&q-url-param-list=&q-signature=7d72652769eb3aad34d09a5a4a66d776fd7cee0d', 'path': '/data/backup/mongodb/full', 'filename': 'Golden-base-bridge-prod_20220310011312.tar', 'download_timeout': 1800, 'region': 'ap-guangzhou', 'instance_id': 'cmgo-7ozf7yh1', 'backup_name': 'cmgo-7ozf7yh1_2022-03-10 01:13'} ]
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: BackupDesc,StartTime,Bucket,BackupMethod,InstanceId,Region,UpdateTime,TaskId fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:2192: Warning: MongosNodeNum,ConfigServerMemory,MongosCpuNum,InstanceTaskDesc,ConfigServerCpuNum,ConfigServerNodeNum,InstanceTaskId,ZoneList,MongosMemory,ConfigServerVolume fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:1202: Warning: Region fileds are useless.
2022-03-12 05:42:49,915 - Traceback (most recent call last):
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/data/python37/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/data/python37/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/data/python37/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/data/python37/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/data/python37/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/python37/lib/python3.7/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/data/python37/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/python37/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/work/dba-in-cloud/libs/myconcurrent.py", line 60, in __single_thread_exe
    self.target(**arg)
  File "/data/work/dba-in-cloud/libs/utils.py", line 99, in download_file_ex
    for data in response.iter_content(chunk_size=chunk_size):
  File "/data/python37/lib/python3.7/site-packages/requests/models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com', port=443): Read timed out.

2022-03-12 05:42:49,924 - fail function use [ {'url': 'https://cmongo-gz-backup-tar-1257588757.cos.ap-guangzhou.myqcloud.com/cmgo-7ozf7yh1_2022-03-12%2001%3A14%2Fcmgo-7ozf7yh1_0.tar?q-sign-algorithm=sha1&q-ak=AKIDhoeKsEVYVaa2zldwGPUOFVaVIuLdHpTw&q-sign-time=1647029939%3B1647116339&q-key-time=1647029939%3B1647116339&q-header-list=host&q-url-param-list=&q-signature=25332ff6b000130b2d29e5791616cbe15c577c25', 'path': '/data/backup/mongodb/full', 'filename': 'Golden-base-bridge-prod_20220312011430.tar', 'download_timeout': 1800, 'region': 'ap-guangzhou', 'instance_id': 'cmgo-7ozf7yh1', 'backup_name': 'cmgo-7ozf7yh1_2022-03-12 01:14'} ]
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: TaskId,UpdateTime,BackupMethod,StartTime,BackupDesc,InstanceId,Region,Bucket fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:2192: Warning: ConfigServerMemory,ConfigServerNodeNum,ConfigServerVolume,InstanceTaskId,MongosCpuNum,InstanceTaskDesc,ConfigServerCpuNum,MongosMemory,MongosNodeNum,ZoneList fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:1202: Warning: Region fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: BackupMethod,Bucket,TaskId,InstanceId,Region,BackupDesc,StartTime,UpdateTime fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:2192: Warning: ConfigServerCpuNum,InstanceTaskId,InstanceTaskDesc,MongosCpuNum,ConfigServerNodeNum,ConfigServerMemory,MongosMemory,ConfigServerVolume,ZoneList,MongosNodeNum fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:1202: Warning: Region fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: Bucket,BackupMethod,Region,UpdateTime,BackupDesc,StartTime,InstanceId,TaskId fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: Bucket,BackupMethod,Region,UpdateTime,BackupDesc,StartTime,InstanceId,TaskId fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:2192: Warning: ConfigServerVolume,InstanceTaskId,ZoneList,InstanceTaskDesc,ConfigServerNodeNum,MongosMemory,ConfigServerMemory,ConfigServerCpuNum,MongosNodeNum,MongosCpuNum fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:1202: Warning: Region fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: BackupMethod,StartTime,UpdateTime,Bucket,InstanceId,Region,TaskId,BackupDesc fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:2192: Warning: ZoneList,MongosMemory,InstanceTaskDesc,ConfigServerCpuNum,ConfigServerVolume,MongosCpuNum,MongosNodeNum,ConfigServerNodeNum,InstanceTaskId,ConfigServerMemory fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:1202: Warning: Region fileds are useless.
/data/python37/lib/python3.7/site-packages/tencentcloud_sdk_python-3.0.426-py3.7.egg/tencentcloud/mongodb/v20190725/models.py:125: Warning: Bucket,BackupDesc,TaskId,StartTime,InstanceId,UpdateTime,Region,BackupMethod fileds are useless.
